### ISSUE TITLE
Setup Yelp API

### ISSUE THREAD

**Issue by DanieleS** [DanieleS/buildo-yelp-training#2]
## Requirements

Setup the basic architecture to query the Yelp API.

## Specs

Implement an `avenger` query to fetch some business from Yelp in some fixed location (i.e. `Milano`).
Print the result as a list in the main view.

**Comment by DanieleS** [comment]
It turns out that the Yelp API doesn't support CORS. To fix this i'm adding a proxy (as docker container) that start together with `yarn start`

**Comment by giogonzo** [comment]
@DanieleS please also feel free to consider a quicker alternative for this project, e.g. to run `npx corsproxy`
