### ISSUE TITLE
Businesses List View

### ISSUE THREAD

**Issue by DanieleS** [DanieleS/buildo-yelp-training#3]
## Requirements

Create a view that shows a businesses list with some basic information.

## Specs

The view should execute the query defined in #2 and show a list of businesses.
Each Business should show:
- Name
- Photo (if available, else show a placeholder)
- Price
- Phone Number
- Rating (and the review count)

**Comment by giogonzo** [comment]
I would also suggest to create some basic but reusable "design system" components. E.g. "Photo (if available, else show a placeholder)" could be a good candidate, in order to reuse it also in the details view
